### PR TITLE
update packages and pragma and compiler versions

### PR DESCRIPTION
**Pull request by eshaben**
This PR updates...
- Dependencies in the package.json
- The version of the Solidity compiler and pragma versions in contracts

### CODE REVIEW

**Comment by eshaben** [comment]
@albertov19 Should we bump the version of this package with these changes?

**Comment by albertov19** [comment]
If you've tested that everything works I don't see why not 😉

**Review by albertov19 — APPROVED** [review]
I'll approve, just make sure all commands are working (also the plugin for example)

**Comment by eshaben** [comment]
Double checked it... everything works as expected! Going to merge it 🚢 

Also, not going to bump the version because just realized this isn't a published package

**Pull request merged**
